# permissions for end users to edit resourcegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: klaudio
    app.kubernetes.io/managed-by: kustomize
  name: resourcegroup-editor-role
rules:
- apiGroups:
  - resources.klaudio.nubank.io
  resources:
  - resourcegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.klaudio.nubank.io
  resources:
  - resourcegroups/status
  verbs:
  - get
