---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - namespaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resources.klaudio.nubank.io
  resources:
  - resourcegroupdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.klaudio.nubank.io
  resources:
  - resourcegroupdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - resources.klaudio.nubank.io
  resources:
  - resourcegroupdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resources.klaudio.nubank.io
  resources:
  - resourcegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.klaudio.nubank.io
  resources:
  - resourcegroups/finalizers
  verbs:
  - update
- apiGroups:
  - resources.klaudio.nubank.io
  resources:
  - resourcegroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resources.klaudio.nubank.io
  resources:
  - resourcerefs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.klaudio.nubank.io
  resources:
  - resourcerefs/finalizers
  verbs:
  - update
- apiGroups:
  - resources.klaudio.nubank.io
  resources:
  - resourcerefs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resources.klaudio.nubank.io
  resources:
  - resources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.klaudio.nubank.io
  resources:
  - resources/finalizers
  verbs:
  - update
- apiGroups:
  - resources.klaudio.nubank.io
  resources:
  - resources/status
  verbs:
  - get
  - patch
  - update
