apiVersion: resources.klaudio.nubank.io/v1alpha1
kind: ResourceRef
metadata:
  labels:
    app.kubernetes.io/name: klaudio
    app.kubernetes.io/managed-by: kustomize
  name: an-infrastructure-resource
spec:
  name: some-infrastructure-resource
  kind: basic-infrastructure
  provisioner:
    name: pulumi
    properties:
      git:
        repo: sample
        branch: main
  schema:
    type: object
    properties:
      name:
        type: string
        description: just a name :)
