apiVersion: resources.klaudio.nubank.io/v1alpha1
kind: ResourceGroup
metadata:
  labels:
    app.kubernetes.io/name: klaudio
    app.kubernetes.io/managed-by: kustomize
  name: my-resource-group
spec:
  resources:
    - name: resourceOne
      resourceRef: pulumi-resource
      properties:
        name: "Tiago"
    - name: resourceTwo
      resourceRef: opentofu-resource
      properties:
        name: ${resources.resourceOne.status.outputs.name}
    - name: resourceThree
      resourceRef: crossplane-resource
      properties:
        name: ${resources.resourceOne.status.outputs.name}
