apiVersion: resources.klaudio.nubank.io/v1alpha1
kind: ResourceRef
metadata:
  labels:
    app.kubernetes.io/name: klaudio
  name: pulumi-resource
spec:
  provisioner:
    name: pulumi
    properties:
      git:
        repo: https://github.com/ljtfreitas/pulumi-sample-project
        branch: main
        dir: just-a-pet/
        intervalInSeconds: 60
  schema:
    type: object
    properties:
      name:
        type: string
        description: just a variable called 'name' :)

---
apiVersion: resources.klaudio.nubank.io/v1alpha1
kind: ResourceRef
metadata:
  labels:
    app.kubernetes.io/name: klaudio
  name: opentofu-resource
spec:
  provisioner:
    name: opentofu
    properties:
      git:
        repo: https://github.com/ljtfreitas/opentofu-sample-project
        branch: main
        dir: random/
        interval: 60s
  schema:
    type: object
    properties:
      name:
        type: string
        description: just a variable called 'name' :)
---
apiVersion: resources.klaudio.nubank.io/v1alpha1
kind: ResourceRef
metadata:
  labels:
    app.kubernetes.io/name: klaudio
  name: crossplane-resource
spec:
  provisioner:
    name: crossplane
    properties:
      objectRef:
        apiVersion: api-extensions.sample.org/v1alpha1
        kind: NullResource
  schema:
    type: object
    properties:
      name:
        type: string
        description: just a variable called 'name' :)
