apiVersion: resources.klaudio.nubank.io/v1alpha1
kind: ResourceGroup
metadata:
  labels:
    app.kubernetes.io/name: klaudio
    app.kubernetes.io/managed-by: kustomize
  name: a-real-infrastructure
spec:
  resources:
    - name: a-real-resource-one
      resourceRef: an-infrastructure-resource
      properties:
        name: just-a-name
    - name: a-real-resource-two
      resourceRef: an-infrastructure-resource
      properties:
        name: ${resources["a-real-resource-one"].spec.properties.name}
