apiVersion: resources.klaudio.nubank.io/v1alpha1
kind: ResourceRef
metadata:
  labels:
    app.kubernetes.io/name: klaudio
  name: resource-one-ref
spec:
  name: resource-one-ref
  kind: basic-infrastructure
  provisioner:
    name: opentofu
    properties:
      git:
        repo: https://github.com/ljtfreitas/opentofu-sample-project
        branch: main
        dir: random/
  schema:
    type: object
    properties:
      name:
        type: string
        description: just a variable called 'name' :)
