apiVersion: resources.klaudio.nubank.io/v1alpha1
kind: ResourceGroupDeployment
metadata:
  labels:
    app.kubernetes.io/name: klaudio
    app.kubernetes.io/managed-by: kustomize
    sample: ola
  name: sample
spec:
  placement: sample
  refs:
    - name: sample
      apiVersion: v1
      kind: ConfigMap
      namespace: default
